### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings.

### ISSUE THREAD

**Issue by ghost** [tolitius/mount-up#3]
When I start my application with `mount-up` in its dependencies, I see the following on the console:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/tf128@ad.uni-heidelberg.de/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/tf128@ad.uni-heidelberg.de/.m2/repository/com/fzakaria/slf4j-timbre/0.3.12/slf4j-timbre-0.3.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```

I use `com.fzakaria/slf4j-timbre` so that Timbre would catch and format all log messages, which mount-up appears to prevent.

Would it be possible to move the functionality requiring logback classic into a separate library?

**Comment by tolitius** [comment]
sure, `logback-classic` is out.
grab `[tolitius/mount-up "0.1.2"]`.
thanks for bringing it up, let me know if it works for you

**Comment by ghost** [comment]
Works! Awesome! Thanks for the quick fix!
